server:
  port: 9000
      
zuul:
  routes:
    catalog-service:
      path: /catalog/**
    reviews-service:
      path: /reviews/**
    recommendations-service:
      path: /recommendations/**
    orders-service:
      path: /orders/**
---

spring:
  profiles: cloud
eureka:
  instance:
    hostname: ms-api-gateway-service.cfapps.io
    nonSecurePort: 80
