server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
    
---

spring:
  profiles: docker
  
eureka:
  client:
    serviceUrl:
      defaultZone: ${APPLICATION_DOMAIN}:8761/eureka/