server:
  port: 8082
  
## Info endpoint
info:
  app:
    name: Recommendations service
    description: Recommendations Microservice
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}


---

spring:
  profiles: cloud
eureka:
  instance:
    hostname: ms-recommendations-service.cf.deepsouthcloud.com
    nonSecurePort: 80