server:
  port: 8082
  
## Info endpoint
info:
  app:
    name: Recommendations service
    description: Recommendations Microservice
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}
    
oauth2:
  resource:
    jwt:
      keyUri: http://localhost:9999/uaa/oauth/token_key
    id: openid
    serviceId: ${PREFIX:}resource
  client:
    tokenUri: http://localhost:9999/uaa/oauth/token
    authorizationUri: http://localhost:9999/uaa/oauth/authorize
    clientId: acme
    clientSecret: acmesecret    


---

spring:
  profiles: cloud
eureka:
  instance:
    hostname: ms-recommendations-service.cf.deepsouthcloud.com
    nonSecurePort: 80