server:
  port: 8081
  
## Info endpoint
info:
  app:
    name: Review service
    description: Review Microservice
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}

---

spring:
  profiles: cloud
eureka:
  instance:
    hostname: ms-reviews-service.cf.deepsouthcloud.com
    nonSecurePort: 80